name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
              channel: stable
              version: 3.22.3

      - name: Go to project
        run: cd filcnaplo

      - name: Flutter pub get (CRITICAL)
        run: |
          cd filcnaplo
          flutter clean
          flutter pub get

      - name: Verify iOS generated files
        run: |
          ls filcnaplo/ios/Flutter

      - name: Install Pods (ONLY AFTER pub get)
        run: |
          cd filcnaplo/ios
          pod install

      - name: Build IPA
        run: |
          cd filcnaplo
          flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: filcnaplo/build/ios/ipa/
